### ISSUE TITLE
The list is incomplete

### ISSUE THREAD

**Issue by FrozenVoid** [JadLevesque/PPMP-Iceberg#2]
Notably functional programming elements can be
 generated with variadic apply() to arglist tuples. 
https://github.com/FrozenVoid/C-headers/blob/main/argmanip.h
GCC expression macro extension is extremely potent 
and seems to be neglected.
https://github.com/FrozenVoid/C-headers/blob/main/lambda.h

**Comment by JadLevesque** [comment]
Functional programming with tuples is already covered in multiple places, namely in articles pertaining to continuation machines (Order-pp, Chaos-pp, Continuation machine). In those instances, evaluation steps scale exponentially instead of linearly.

As for GCC's statement expressions, they are not common enough and are unrelated to the preprocessor.
